---
# yamllint disable rule:line-length
name: Windows build

on:
  push:
    branches:
      - main
      - win64
    paths-ignore:
      - 'manual/**'
    tags:
      - '*'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'manual/**'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}


jobs:
  build:
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows MSVC 32-bit
            runner: windows-latest
            platform: win32
            generator_platform: Win32
            vs_arch: win32
            target_tuple: msvc-wx32;10;x86
          - name: Windows MSVC 64-bit
            runner: windows-latest
            platform: x64
            generator_platform: x64
            vs_arch: x64
            target_tuple: msvc-64;10;x86_64

    env:
      PLATFORM: ${{ matrix.platform }}
      wxGTK_VERSION: ${{ matrix.gtk_version && matrix.gtk_version || 3 }}

    # Use bash as the shell, even under MSW where the default is PowerShell.
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # required for CMake to find Ninja
      - name: "[Windows] Set up MSVC Developer Command Prompt"
        if: runner.os == 'Windows'
        uses: seanmiddleditch/gha-setup-vsdevenv@v3
        with:
          host_arch: x86
          arch: ${{ matrix.vs_arch }}

      - name: "[Windows] Dependencies, configure, build"
        if: runner.os == 'Windows'
        run: |
          call buildwin/win_deps.bat
          cmake -A ${{ matrix.generator_platform }} -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DOCPN_TARGET_TUPLE=${{ matrix.target_tuple }} -T v143 -DWITH_TESTS=OFF -DCMAKE_CXX_STANDARD=17
          cmake --build build --config ${{env.BUILD_TYPE}}
        shell: cmd
      - name: "[Windows] Publish to Cloudsmith"
        if: runner.os == 'Windows'
        run: |
          cd build
          .\upload.bat
        shell: cmd
...
